//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImgTrackTrimmer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200, 200")]
        public global::System.Drawing.Point DefaultLoc {
            get {
                return ((global::System.Drawing.Point)(this["DefaultLoc"]));
            }
            set {
                this["DefaultLoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("407, 183")]
        public global::System.Drawing.Size DefaultSize {
            get {
                return ((global::System.Drawing.Size)(this["DefaultSize"]));
            }
            set {
                this["DefaultSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal VStartX {
            get {
                return ((decimal)(this["VStartX"]));
            }
            set {
                this["VStartX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal VStartY {
            get {
                return ((decimal)(this["VStartY"]));
            }
            set {
                this["VStartY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal VEndX {
            get {
                return ((decimal)(this["VEndX"]));
            }
            set {
                this["VEndX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal VEndY {
            get {
                return ((decimal)(this["VEndY"]));
            }
            set {
                this["VEndY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("582, 442")]
        public global::System.Drawing.Size PicSize {
            get {
                return ((global::System.Drawing.Size)(this["PicSize"]));
            }
            set {
                this["PicSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("742, 492")]
        public global::System.Drawing.Size Deff {
            get {
                return ((global::System.Drawing.Size)(this["Deff"]));
            }
            set {
                this["Deff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("784, 522")]
        public global::System.Drawing.Size DefSize {
            get {
                return ((global::System.Drawing.Size)(this["DefSize"]));
            }
            set {
                this["DefSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("784, 522")]
        public global::System.Drawing.Size DeffSize {
            get {
                return ((global::System.Drawing.Size)(this["DeffSize"]));
            }
            set {
                this["DeffSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("349, 121")]
        public global::System.Drawing.Size DeffPicSize {
            get {
                return ((global::System.Drawing.Size)(this["DeffPicSize"]));
            }
            set {
                this["DeffPicSize"] = value;
            }
        }
    }
}
